### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fj-morales** [vgrabovets/multi_rake#36]
Hi!

I am interested in using your tool, but when I try to install it, I receive this error:

`    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/setup.py", line 191, in <module>
        'Topic :: Text Processing :: Linguistic'
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/francisco/.local/share/virtualenvs/rake-MKMDuRw-/lib/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib/python3.6/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/setup.py", line 143, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/setup.py", line 128, in get_ext_modules
        import cld2
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/cld2/__init__.py", line 190, in <module>
        extra_compile_args=_COMPILER_ARGS)
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/api.py", line 468, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/tmp/pip-install-uu14tt9z/cld2-cffi/.eggs/cffi-1.14.0-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by vgrabovets** [comment]
Hi! This is problem with C compiler. 
Try `CFLAGS="-Wno-narrowing" pip install cld2-cffi` and than `pip install multi-rake`
If it still doesn't work, make sure that you have all necessary libraries installed on your machine.
`sudo apt-get install build-essential python3-dev`

**Comment by ahmedbr** [comment]
> Hi! This is problem with C compiler.
> Try `CFLAGS="-Wno-narrowing" pip install cld2-cffi` and than `pip install multi-rake`
> If it still doesn't work, make sure that you have all necessary libraries installed on your machine.
> `sudo apt-get install build-essential python3-dev`

Thanks, this worked for me

**Comment by vgrabovets** [comment]
Switched from cld2 to pycld2, installation issues should be fixed.
